fix(linux/getroot): undefined reference to `makedev'
"#include <sys/sysmacros.h>" was removed from "sys/types.h",
thus we got an error:
```
libgrubkern.a(libgrubkern_a-getroot.o): In function `grub_util_biosdisk_is_floppy':
getroot.c:(.text+0x11d2): undefined reference to `major'
libgrubkern.a(libgrubkern_a-getroot.o): In function `grub_util_raid_getmembers':
getroot.c:(.text+0x33a): undefined reference to `makedev'
```

This commit fixes the error.